A puriasova homework 26 completed
eugene-okulik/puraleksa pull request #11
Opened 2024-05-22 02:12 UTC by apuryasova

2024-05-22 15:24 UTC, eugene-okulik requested changes
Автотесты, как и любая программа, нуждаются в тестировании. И после создания автотестов очень хорошим тоном будет посмотреть, что они действительно делают то, что должны.

2024-05-22 15:24 UTC, eugene-okulik commented on homework/a_puriasova/homework26/test_one.py
> +    field2 = page.get_by_label("Password")
Ай-ай-ай. Найдено не по роли.

2024-05-22 15:24 UTC, eugene-okulik commented on homework/a_puriasova/homework26/test_two.py
> +    page.get_by_placeholder("Mobile Number").fill("111330633")
Мобильный номер не проходит валидацию.

2024-05-22 15:24 UTC, eugene-okulik commented on homework/a_puriasova/homework26/test_two.py
> +    page.locator("#subjectsInput").fill("hgjkhkj")
Это поле после сабмита осталось незаполненным.

2024-05-22 15:24 UTC, eugene-okulik commented on homework/a_puriasova/homework26/test_two.py
> +    # если это можно было сделать по другому - напиши пожалуйста
Скорее всего, плейрайт бы сам тебе подсказал при запуске.

2024-05-22 16:38 UTC, apuryasova commented on homework/a_puriasova/homework26/test_two.py
> +    page.get_by_placeholder("Mobile Number").fill("111330633")
а блин я забыла исправить в коде - цифры не хватило

2024-05-22 16:41 UTC, apuryasova commented on homework/a_puriasova/homework26/test_one.py
> +    field2 = page.get_by_label("Password")
в доке поролям написано, что input type=password [No corresponding role] тогда как по роли сделать?))

2024-05-23 02:35 UTC, apuryasova commented on homework/a_puriasova/homework26/test_two.py
> +    page.locator("#subjectsInput").fill("hgjkhkj")
какое поле? все поля заполнены

2024-05-23 15:17 UTC, eugene-okulik commented on homework/a_puriasova/homework26/test_two.py
> +    page.locator("#subjectsInput").fill("hgjkhkj")
Поставь слип после сабмита или даже до и посмотри на это поле. Оно будет пустым

2024-05-29 11:51 UTC, merged