Puraleksa: update homework 26
eugene-okulik/puraleksa pull request #12
Opened 2024-05-23 02:36 UTC by apuryasova

2024-05-23 15:19 UTC, eugene-okulik requested changes
А чего на одно задание два пулл реквеста?

2024-05-23 15:19 UTC, eugene-okulik commented on homework/a_puriasova/homework26/test_two.py
> +    # он не может выполнить это действие - там реклама перекрывает, не получается ее закрыть
Можно поиграться с  размером браузера, тогда элементы перераспределяются.

2024-05-23 20:14 UTC, apuryasova commented on homework/a_puriasova/homework26/test_two.py
> +    # он не может выполнить это действие - там реклама перекрывает, не получается ее закрыть
аможно было обойтись одним пулреквестом?

2024-05-24 13:09 UTC, eugene-okulik commented on homework/a_puriasova/homework26/test_two.py
> +    # он не может выполнить это действие - там реклама перекрывает, не получается ее закрыть
Ну да, ты же внесла изменения в ту же ветку. Вот они в том же пул реквесте и отобразились. А ты ни разу еще за весь курс не исправляла ничего?

2024-05-27 01:37 UTC, apuryasova commented on homework/a_puriasova/homework26/test_two.py
> +    # он не может выполнить это действие - там реклама перекрывает, не получается ее закрыть
нет, разные ветки, надо в одну?))))

2024-05-27 15:07 UTC, eugene-okulik commented on homework/a_puriasova/homework26/test_two.py
> +    # он не может выполнить это действие - там реклама перекрывает, не получается ее закрыть
Одно задание делается в одной ветке, да. И исправления по этому заданию делаются тоже в той же ветке.

2024-05-29 11:51 UTC, merged