puraleksa: update homework26.2
eugene-okulik/puraleksa pull request #13
Opened 2024-05-27 01:42 UTC by apuryasova

изменила размер браузера и это не помогло - оставила в коде на всякий случай, помогло только выполнение клика на кнопку с использованием JavaScript
какой выход?
у меня сейчас на работе как раз тесты умали на селениуме потому что там реклама так же внизу экрана и я не знаю как это глобально решить, хэлп плиззззззз!

2024-05-27 01:43 UTC, apuryasova commented
поняла, что можно в одну ветку - но по привычкие

2024-05-27 15:09 UTC, eugene-okulik commented
> изменила размер браузера и это не помогло - оставила в коде на всякий случай, помогло только выполнение клика на кнопку с использованием JavaScript какой выход? у меня сейчас на работе как раз тесты умали на селениуме потому что там реклама так же внизу экрана и я не знаю как это глобально решить, хэлп плиззззззз!

Когда у тебя на работе так тесты падают - заводи баг. Реклама не должна перекрывать элементы интерфейса или должна быть закрываемой.

2024-05-27 15:13 UTC, eugene-okulik requested changes

2024-05-27 15:13 UTC, eugene-okulik commented on homework/a_puriasova/homework26/test_two.py
> +    page.locator("#subjectsInput").fill("hgjkhkj")
После сабмита это поле всё еще остается пустым. Да и до сабмита. Как только ты уходишь от этого поля, оно остается пустым. Заполняется оно только подсказками, которые возникают, когда вводишь текст.

2024-05-28 14:14 UTC, apuryasova commented on homework/a_puriasova/homework26/test_two.py
> +    page.locator("#subjectsInput").fill("hgjkhkj")
то есть его нужно как то принудить заполнятся??))) оно не заполняется, пошла думать

2024-05-28 16:33 UTC, apuryasova commented
Поняла в чем проблема была, не сразу заметила, что в том поле выпадашка))

2024-05-29 11:50 UTC, eugene-okulik approved these changes

2024-05-29 11:50 UTC, eugene-okulik commented on homework/a_puriasova/homework26/test_two.py
> +    page.get_by_text("Maths", exact=True).click()
:+1:

2024-05-29 11:51 UTC, merged