a_puriasova: homework4 completed
eugene-okulik/puraleksa pull request #3
Opened 2024-03-19 14:58 UTC by apuryasova

2024-03-19 16:59 UTC, eugene-okulik requested changes
Всё хорошо, но одну проверку на внимательность не прошла.

2024-03-19 16:59 UTC, eugene-okulik commented on homework/a_puriasova/homework4/dict.py
> +my_dict['dict']['i am a tuple'] = 'value6'  # Добавляем новый элемент
В задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

Ты выполнила так, как если бы в задании было

> добавьте элемент с ключом 'i am a tuple' и любым значением

Задумка в том, что ключом здесь должен быть кортеж с одним элементом, который выглядит ровненько так, как написано в задании. А сейчас у тебя ключ - строка.  
Ну и на занятии я показывал как выглядит кортеж с одним элементом.

2024-03-20 01:54 UTC, apuryasova commented on homework/a_puriasova/homework4/dict.py
> +my_dict['dict']['i am a tuple'] = 'value6'  # Добавляем новый элемент
окей, поняла - переделаю!

2024-03-20 14:11 UTC, eugene-okulik approved these changes

2024-03-20 14:11 UTC, merged