a_puriasova homework8 done
eugene-okulik/puraleksa pull request #7
Opened 2024-04-09 01:32 UTC by apuryasova

2024-04-09 15:17 UTC, eugene-okulik requested changes

2024-04-09 15:17 UTC, eugene-okulik commented on homework/a_puriasova/homework8/2.py
Задание состяло из двух частей:
1. Создать генератор, который генерирует числа фибоначчи
2. Создать код, который получая числа из генератора, распечатает пятое, двухсотое....

Сейчас в решении есть функция, которая распечатывает пятое, двухсотое.... число из чиел фибоначчи. Если бы задание было сформулировано так, то решение было бы ок. Но в задании сказано, что нужно сделать функцию-генератор.

2024-04-09 17:20 UTC, apuryasova commented on homework/a_puriasova/homework8/2.py
хм, окей попробую разобраться, спасибо

2024-04-09 19:01 UTC, eugene-okulik requested changes

2024-04-09 19:01 UTC, eugene-okulik commented on homework/a_puriasova/homework8/2.py
> +        num += n
Уже лучше, осталось, чтобы этот генератор генерировал не прогрессию, а числа фибоначчи. Остальное все ок.

2024-04-10 17:47 UTC, apuryasova commented on homework/a_puriasova/homework8/2.py
> +        num += n
окей, добавила два варианта, больше не знаю как решить ))

2024-04-11 11:33 UTC, eugene-okulik approved these changes
Отлично!

2024-04-11 11:33 UTC, merged